easy_admin:
#    resource : '@EasyAdminBundle/Controller/EasyAdminController.php'
    # On définit le nom de l'interface d'administration
    site_name: 'Joseph-Watch e-commerce'
    # On définit l'affichage de l'utilisateur
    user:
        display_name: true
        display_avatar: true
    formats:
        date:     'd/m/Y'
        time:     'H:i'
        datetime: 'd/m/Y H:i:s'
    design:
        form_theme:
            - "@EasyAdmin/form/bootstrap_4.html.twig"
        # Ces lignes définiront notre menu
        menu:
            - { label: 'Boutique' }
            - { label: 'Boutique', route: 'boutique', icon: 'home' }
            - { label: 'Produits' }
            - { entity: 'Product', label: 'Produit', icon: 'clock' }
            - { label: 'Utilisateurs' }
            - { entity: 'User', label: 'Utilisateurs', icon: 'user' }
            - { label: 'Commandes' }
            - { entity: 'Order', label: 'Commandes', icon: 'list' }
            - { label: 'Dashboard' }
            - { label: 'Paiement', url: 'https://dashboard.stripe.com/test/dashboard', target: '_blank'
              , icon: 'credit-card' }
    entities:
        Product:
            # Correspond au fichier Product.php
            class: App\Entity\Product
            # On définit ci-dessous le contenu de la liste qui affichera les articles et les critères de tri
            list:
                fields:
                    - id
                    - name
                    # Le champ ci-dessous affichera l'image de product
                    - { property: 'image', type: 'image', base_path: 'Img-Boutique-e-commerce' }
                    - { property: 'reference', label: 'réf.' }
                    - { property: 'price', label: 'prix'}
                    - { property: 'quantity', label: 'quantité'}
                    - { property: 'description', label: 'description'}
                    - { property: 'cases', label: 'boitîer'}
                    - bracelet
            form:
                fields:
                    - name
                    - { property: 'imageFile', type: 'vich_image' }
                    - { property: 'reference', label: 'Réf.' }
                    - { property: 'price', label: 'Prix'}
                    - { property: 'quantity', label: 'Quantité'}
                    - { property: 'description', label: 'Description'}
                    - { property: 'category', label: 'Categorie'}
                    - { property: 'cases', label: 'Boitîer'}
                    - bracelet
        User:
            class: App\Entity\User
            label: 'Utilisateurs'
            list:
                fields:
                    - id
                    - email
                    - {property: 'firstname', label: 'Prénom'}
                    - {property: 'lastname', label: 'Nom'}
                    - { property: 'roles', label: 'Rôles', type: json_array}
                    - {property: 'orders', label: 'Commandes'}

            form:
                field:
                    - property: 'civility'
                      label: 'civilité'
                      type: 'choice'
                      type_options:
                          choices:
                            Monsieur: 'M.'
                            Madame: 'Mme'
                            Autre: 'Autre'
                          multiple: false
                          expanded: true
                    - { property: 'firstname', label: 'Prénom'}
                    - { property: 'lastname', label: 'Nom'}
                    - email
                    - { property: 'password', label: 'Mot de passe'}
                    - property: 'roles'
                      label: 'roles'
                      type: 'choice'
                      type_options:
                          choices:
                            Utilisateur: 'ROLE_USER'
                            Administrateur: 'ROLE_ADMIN'
                          multiple: true
                          expanded: true

        Order:
            class: App\Entity\Order
            label: Commandes

            


